name: ci
on: push
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Print GitHub CI variables
        run: npx @bahmutov/print-env GITHUB
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
        # pass CI run information via Cypress_ variables
        # to make it readily available in Cypress specs and support files
        env:
          CYPRESS_runId: ${{ github.run_id }}
          CYPRESS_runNumber: ${{ github.run_number }}
          CYPRESS_runAttempt: ${{ github.run_attempt }}
          CYPRESS_jobName: ${{ github.job }}
